### ISSUE TITLE
百度云 ORC 配置好像有问题

### ISSUE THREAD

**Issue by Mervyen** [wangtonghe/hq-answer-assist#11]
![100ce23d0fe5ff06f0472aaa727cf6e](https://user-images.githubusercontent.com/35766443/35333539-0c65962c-014a-11e8-9384-5ba0dfe76cbb.png)
我的百度云配置好像有我问题   我是python27  不是3
请问这是哪里出问题了

**Comment by Mervyen** [comment]
我下面挡住的是我的百度云ID和秘钥等等

**Comment by wangtonghe** [comment]
@Mervyen  看报错没发现什么，我百度ocr的`api_key`写成了`api_ley`(已修改)，但应该对你没影响，确认下是否安装了百度ocr的SDK,`pip install baidu-aip`，或还有其他有用的报错信息吗？

**Comment by Mervyen** [comment]
谢谢您，那个api_key和api_ley我看明白了。。。
我已经装了baidu-aip  但是我是python27  我现在装了个3  但是pip 库好像出问题了。。我现在在百度怎么win下运行同时用27和3。。。还在调
谢谢谢谢谢。。

**Comment by Mervyen** [comment]
![image](https://user-images.githubusercontent.com/35766443/35341006-9377233c-015f-11e8-8d01-bd1268e76c95.png)
出现这个问题了。。我还是用的27  
我把utils.py里面的import部分的urllib.question改成了urllib
seach.py里面的imort部分的urllib.question改成了urllib
不改的话会报错。@wangtonghe

**Comment by wangtonghe** [comment]
@Mervyen 哦，目前反映python2确实会有问题，解决了就好。我是按python3写的，后续可能会考虑兼容
