### ISSUE TITLE
运行出现如下错误是chi_sim.traineddata安装的有问题吗？

### ISSUE THREAD

**Issue by leohuangyy** [wangtonghe/hq-answer-assist#9]
PS D:\github\hq-answer-assist> python main.py
Ret=0Ret=0Ret=0Ret=0Traceback (most recent call last):
  File "main.py", line 96, in <module>
    main()
  File "main.py", line 71, in main
    question, option_arr, is_negative = analyze.image_to_str(crop_obj, is_baidu_ocr, baidu_ocr_clint)  # 图片转文字
  File "D:\github\hq-answer-assist\analyze.py", line 51, in image_to_str
    question, option_arr = tesseract_orc(image)
  File "D:\github\hq-answer-assist\analyze.py", line 58, in tesseract_orc
    text = pytesseract.image_to_string(image, lang='chi_sim')
  File "C:\Users\huangyy\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pytesseract\pytesseract.py", line 1
25, in image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\chi_sim.train
eddata')

**Comment by wangtonghe** [comment]
@leohuangyy  看样子是的，请检查chi_sim.traineddata文件是否存在于Tesseract目录下。

你也可以使用百度的ocr接口，具体配置可参见README文档

**Comment by leohuangyy** [comment]
chi_sim.traineddata文件已经存在于Tesseract目录下，而且我环境变量我也加了。还是会出这个错误。

**Comment by leohuangyy** [comment]
问题已解决，方法是在pytesseract中加入tessdata_dir_config = '--tessdata-dir "C:\\Program Files (x86)\\Tesseract-OCR\\tessdata"'
